apiVersion: v2
name: thanos-bucket-config
icon: https://raw.githubusercontent.com/thanos-bucket-config/thanos-bucket-config.github.io/master/assets/thanos-bucket-config_logo-cb55bb5c346.png
description: A Weaveworks Helm chart for thanos bucket configurations
type: application
version: 0.0.5
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog

keywords:
- operator
- thanos-bucket-config

annotations:
  "weave.works/category": Observability
  "weave.works/operator": "true"
  "weave.works/layer": layer-0
  "weave.works/profile-ci": |
    - "gke"
    - "kind"

maintainers:
  - name: Weaveworks
    email: support@weave.works
